import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next ToDoList",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cupcake">
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body className={"${inter.className} text-slate-100 mx-auto p-4"}>
        {children}
      </body>
    </html>
  );
}
